# Job properties
jobname: jobname    # Name of the job
rundir: rundir      # Where the job area is going to be written
walltime: walltime  # Walltime limit for job


# Machine properties -- Probably need reilated things to this
machine: machine        # Info about the system where you're running
name: name              # Cheetah name for the machine
job_setup: job_setup    # Setup that runs in the job script before the main run
submit_setup: submit_setup    # Setup that runs in the job script before the main run
scheduler_args: scheduler_args

setup_file: setup_file  # File to source per code for setup


# Copying type parameters
copy: copy                      # Hard copying -- Directories copy as a single entity into the target
copycontents: copy-contents     # Hard copying -- Contents of directories copy, not the single top directory as an entity
link: link                      # Make symboloic link


# Setup type parameters
pre-sub-cmds: pre-submit-commands  # Commands that run before submitting the job, to set up up the working area
file-edit: file-edit


# Other
include: include
mpmd: mpmd
script: script
login-proc: login-proc
timed: timed
node-share: node-share
share-nodes: share-nodes
env: env


path: executable_path
args: commandline_args
options: commandline_options
filename: output_path
engine: adios_engine
params: adios_engine_params
processes: processes
processes-per-node: processes-per-node

use-dashboard: use-dashboard
dashboard: dashboard
backup: backup
